// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vznmyiltsbkdgzuenecs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ6bm15aWx0c2JrZGd6dWVuZWNzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwNDc3MDcsImV4cCI6MjA2MDYyMzcwN30.0yqgnLawgoxo0Z5_fi0rZckO6itIwm1OdzV6pySW2tU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);